
package MainProgram;

import Database.Koneksi;
import static MainProgram.Menu.namauser;
import com.sun.glass.events.KeyEvent;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Fajar Adi Setyawan
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    public Connection con;
    public ResultSet rs;
    public Statement st;
    Object set;
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        Koneksi classKoneksi = new Koneksi();
        con = classKoneksi.getKoneksi();
    }

    private void login(){
        String user = Input_Username.getText();
        String pass = Input_Password.getText();

        try{
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM tb_user WHERE username='"+ user + "' AND password='" + pass +"'");
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Login Berhasil " + user, "Pemberitahuan", JOptionPane.PLAIN_MESSAGE);
                namauser.setText(rs.getString(3));
                
                new Menu().setVisible(true);
                this.dispose();
            }else  {
                JOptionPane.showMessageDialog(null, "Username & Password TIDAK ditemukan !", "Pemberitahuan", JOptionPane.ERROR_MESSAGE);
            }
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Berhasil Login", ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Input_Username = new MainProgram.CustomTextField();
        jLabel4 = new javax.swing.JLabel();
        Input_Password = new MainProgram.CustomPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        show = new javax.swing.JLabel();
        hide = new javax.swing.JLabel();
        Button_Login = new javax.swing.JButton();
        Button_Exit = new javax.swing.JButton();
        Button_Minimize = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(java.awt.Color.darkGray);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainProgram/Image/icons8_user_male_circle_35px_1.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 45, -1, -1));

        Input_Username.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Input_Username.setBorder(null);
        Input_Username.setNextFocusableComponent(Input_Password);
        Input_Username.setOpaque(false);
        jPanel2.add(Input_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 45, 189, 35));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainProgram/Image/icons8_password_35px.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 117, -1, -1));

        Input_Password.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Input_Password.setBorder(null);
        Input_Password.setNextFocusableComponent(Button_Login);
        Input_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Input_PasswordKeyPressed(evt);
            }
        });
        jPanel2.add(Input_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 117, 170, 35));

        jLabel3.setFont(new java.awt.Font("CamingoCode", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 337, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 80, 189, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 152, 189, 10));

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainProgram/Image/icons8_visible_20px.png"))); // NOI18N
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        jPanel2.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainProgram/Image/icons8_invisible_20px.png"))); // NOI18N
        hide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideMouseClicked(evt);
            }
        });
        jPanel2.add(hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        Button_Login.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Button_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainProgram/Image/Login.png"))); // NOI18N
        Button_Login.setBorder(null);
        Button_Login.setBorderPainted(false);
        Button_Login.setContentAreaFilled(false);
        Button_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Login.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MainProgram/Image/LoginS.png"))); // NOI18N
        Button_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_LoginMouseClicked(evt);
            }
        });
        jPanel2.add(Button_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 100, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 210));

        Button_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainProgram/Image/CloseB25px.png"))); // NOI18N
        Button_Exit.setBorder(null);
        Button_Exit.setBorderPainted(false);
        Button_Exit.setContentAreaFilled(false);
        Button_Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Button_Exit.setOpaque(true);
        Button_Exit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MainProgram/Image/Close25pxS.png"))); // NOI18N
        Button_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_ExitMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 30));

        Button_Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainProgram/Image/MinimizeB.png"))); // NOI18N
        Button_Minimize.setBorder(null);
        Button_Minimize.setBorderPainted(false);
        Button_Minimize.setContentAreaFilled(false);
        Button_Minimize.setOpaque(true);
        Button_Minimize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MainProgram/Image/Minimisize25pxS.png"))); // NOI18N
        Button_Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_MinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainProgram/Image/icons8_shop_25px.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel6.setText("Buat Akun Baru ?");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ExitMouseClicked
        int opt = JOptionPane.showConfirmDialog(null, "KELUAR ?", "KELUAR", JOptionPane.YES_NO_OPTION);
        if(opt==0){
            System.exit(0);
        }
    }//GEN-LAST:event_Button_ExitMouseClicked

    private void Button_MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_MinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_Button_MinimizeMouseClicked

    private void Button_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_LoginMouseClicked
        login();
    }//GEN-LAST:event_Button_LoginMouseClicked

    private void Input_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Input_PasswordKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            login();
        }
    }//GEN-LAST:event_Input_PasswordKeyPressed

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        hide.setVisible(true);
        hide.setEnabled(true);
        Input_Password.setEchoChar((char)0);
        show.setVisible(false);
        show.setEnabled(false);
    }//GEN-LAST:event_showMouseClicked

    private void hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseClicked
        show.setVisible(true);
        show.setEnabled(true);
        Input_Password.setEchoChar((char)8226);
        hide.setVisible(false);
        hide.setEnabled(false);
    }//GEN-LAST:event_hideMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        new SignUp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Exit;
    private javax.swing.JButton Button_Login;
    private javax.swing.JButton Button_Minimize;
    private javax.swing.JPasswordField Input_Password;
    private javax.swing.JTextField Input_Username;
    private javax.swing.JLabel hide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel show;
    // End of variables declaration//GEN-END:variables
}
