/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainProgram;

import java.awt.print.PrinterException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;

/**
 *
 * @author Fajar Adi Setyawan
 */
public class Print extends javax.swing.JFrame {

    /**
     * Creates new form Print
     */
    public Print() {
        initComponents();
    }
   
    Calendar kal = new GregorianCalendar();
    int tahun = kal.get(Calendar.YEAR);
    int bulan = kal.get(Calendar.MONTH)+1;
    int hari = kal.get(Calendar.DAY_OF_MONTH);
    int jam = kal.get(Calendar.HOUR_OF_DAY);
    int menit = kal.get(Calendar.MINUTE);
    //int detik = kal.get(Calendar.SECOND);
    String tanggal = hari + " / " + bulan + " / " + tahun;
    String waktu = jam + ":" + menit;
    String txt_sub;
    String txt_bayar;
    String txt_kembalian;
    
    public Print(String subtotal, String bayar, String kembalian, TableModel model){
        initComponents();
        
        this.txt_sub = subtotal;
        this.txt_bayar = bayar;
        this.txt_kembalian = kembalian;
        
        txt_print.setText(txt_print.getText() + "------------------------------------------------------------------------------------\n");
        txt_print.setText(txt_print.getText() + "======================Struk======================\n");
        txt_print.setText(txt_print.getText() + "------------------------------------------------------------------------------------\n");
        txt_print.setText(txt_print.getText() + tanggal + "\n");
        txt_print.setText(txt_print.getText() + waktu + "\n");
        txt_print.setText(txt_print.getText() + "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n");
        txt_print.setText(txt_print.getText() + "\nNama Baju\t" + "Harga\t" + "Qyt\t" + "Total\n");
        
        for(int i = 0; i < model.getRowCount(); i++){
            String nama = (String) model.getValueAt(i, 1);
            String harga = (String) model.getValueAt(i, 2);
            String qyt = (String) model.getValueAt(i, 3);
            int total = (int) model.getValueAt(i, 4);
            txt_print.setText(txt_print.getText() + nama + "\t" + harga +"\t" + qyt + "\t" + total + "\n");
        }
        
        txt_print.setText(txt_print.getText() + "\n\n");
        txt_print.setText(txt_print.getText() + "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n");
        txt_print.setText(txt_print.getText() + "\t\t" + "Subtotal\t:" + subtotal +  "\n");
        txt_print.setText(txt_print.getText() + "\t\t" + "Bayar\t:" + bayar +  "\n");
        txt_print.setText(txt_print.getText() + "\t\t" + "Kembalian\t:" + kembalian +  "\n\n");
        txt_print.setText(txt_print.getText() + "------------------------------------------------------------------------------------\n");
        txt_print.setText(txt_print.getText() + "\t   Terima Kasih\n");
        txt_print.setText(txt_print.getText() + "------------------------------------------------------------------------------------\n");
        
        try {
            txt_print.print();
        } catch (PrinterException ex) {
            System.out.println(ex);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txt_print = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txt_print.setEditable(false);
        txt_print.setColumns(20);
        txt_print.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt_print.setRows(5);
        txt_print.setBorder(null);
        jScrollPane2.setViewportView(txt_print);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt_print;
    // End of variables declaration//GEN-END:variables
}
